# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    stable:
      rustup_toolchain: stable
    beta:
      rustup_toolchain: beta
    nightly:
      rustup_toolchain: nightly

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: install rust
  - script: cargo build --all
    displayName: build debug
  - script: cargo test --package lta --lib tests --all-features
    env:
      API_KEY: $api_key
    displayName: test with actual endpoints
  - script: cargo test --package lta --lib tests::fut --all-features
    displayName: test futures
  - script: cargo test --package lta_models --lib tests
    displayName: test serde