[package]
name = "lta"
version = "0.3.0-beta"
authors = ["budinverse <budisyahiddin@gmail.com>"]
edition = "2018"
homepage = "https://github.com/BudiNverse/lta-rs"
repository = "https://github.com/BudiNverse/lta-rs"
description = "🚍 Singapore LTA Datamall Rust Client written in pure rust with support for asynchronous requests"
readme = "README.md"
license = "MIT"
keywords = ["LTA", "Singapore", "Client", "Datamall"]
exclude = ["/.travis.yml", "/logo.png", "./azure-pipelines.yml", "./dumped_data", "./benches"]

[lib]
name = "lta"

[features]
async = ["lta_async"]
blocking = ["lta_blocking"]

[dependencies]
lta_async = { path = "lta_async", optional = true }
lta_blocking = { path = "lta_blocking", optional = true }
lta_models = { path = "lta_models", optional = false }
lta_utils_commons = { path = "lta_utils_commons", optional = false }

[dev-dependencies]
tokio = "0.2.4"

[workspace]
members = [
    "lta_async",
    "lta_models",
    "lta_blocking",
    "lta_utils_commons",
]
