[package]
name = "lta"
version = "0.3.0-async-preview-1"
authors = ["budinverse <budisyahiddin@gmail.com>"]
edition = "2018"
homepage = "https://github.com/BudiNverse/lta-rs"
repository = "https://github.com/BudiNverse/lta-rs"
description = "🚍 Singapore LTA Datamall Rust Client written in pure rust with support for asynchronous requests"
readme = "README.md"
license = "MIT"
keywords = ["LTA", "Singapore", "Client", "Datamall"]
exclude = ["/.travis.yml"]

[lib]
name = "lta"

[features]
async = ["async"]

[dependencies]
reqwest = "0.9.19"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
lazy_static = "1.3.0"
regex = "1.2.0"
chrono = { version = "0.4.7", features = ["serde"] }
futures-preview = "0.3.0-alpha.17"
tokio = "0.1.22"