[package]
name = "lta"
version = "0.1.0"
authors = ["budi <budisyahiddin@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.4"
lazy_static = "1.3.0"
regex = "1"
chrono = "0.4"