[package]
name = "lta"
version = "0.3.0-async-preview-6"
authors = ["budinverse <budisyahiddin@gmail.com>"]
edition = "2018"
homepage = "https://github.com/BudiNverse/lta-rs"
repository = "https://github.com/BudiNverse/lta-rs"
description = "🚍 Singapore LTA Datamall Rust Client written in pure rust with support for asynchronous requests"
readme = "README.md"
license = "MIT"
keywords = ["LTA", "Singapore", "Client", "Datamall"]
exclude = ["/.travis.yml", "/logo.png", "./azure-pipelines.yml", "./dumped_data", "./benches"]

[lib]
name = "lta"

[features]
async = ["lta_async"]
blocking = ["lta_blocking"]
default = ["lta_async", "lta_blocking"]

[dependencies]
reqwest = "0.9.19"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
lazy_static = "1.3.0"
regex = "1.3.0"
chrono = { version = "0.4.7", features = ["serde"] }
futures = "0.1.28"
lta_async = { path="./lta_async", optional = true }
lta_blocking = { path="./lta_blocking", optional = true }
lta_models = { path="./lta_models", optional = false }
lta_utils_commons = { path="./lta_utils_commons", optional = false }

[dev-dependencies]
tokio = "0.1.22"
criterion = "0.3"

[workspace]
members = [
    "lta_async",
    "lta_utils_commons",
    "lta_models",
    "lta_blocking"
]

[[bench]]
name = "benchmark"
harness = false
