[package]
name = "lta"
version = "0.2.2"
authors = ["budinverse <budisyahiddin@gmail.com>"]
edition = "2018"
description = "🚍 Singapore LTA Datamall Rust Client written in pure rust"
readme = "README.md"
license-file = "LICENSE"
keywords = ["LTA", "Singapore", "Client"]

[dependencies]
reqwest = "0.9.19"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
lazy_static = "1.3.0"
regex = "1.2.0"
chrono = { version = "0.4.7", features = ["serde"]}