[package]
name = "lta"
version = "0.4.0"
authors = ["budinverse <budisyahiddin@gmail.com>"]
edition = "2018"
homepage = "https://github.com/BudiNverse/lta-rs"
repository = "https://github.com/BudiNverse/lta-rs"
description = "🚍 Singapore LTA Datamall Rust Client written in pure rust with support for asynchronous requests"
readme = "README.md"
license = "MIT"
keywords = ["LTA", "Singapore", "Client", "Datamall"]
exclude = [
    "/.travis.yml",
    "/logo.png",
    "./azure-pipelines.yml",
]

[lib]
name = "lta"

[features]
default = ["async-trait"]
blocking = ["reqwest/blocking"]

[dependencies]
lta_models = { git = "https://github.com/lta-rs/lta-models.git", branch = "main" }
reqwest = { version = "0.11", features = ["json", "rustls"] }
serde = { version = "1.0.118" }
async-trait = { version = "0.1.42", optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros"]}